# Generated by Django 3.0.6 on 2020-05-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTextEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('content', models.TextField()),
                ('imported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
