# Generated by Django 3.0.6 on 2020-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytextentry',
            name='audio_file_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytextentry',
            name='audio_file_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytextentry',
            name='audio_file_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailytextentry',
            name='book_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailytextentry',
            name='chapter_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailytextentry',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailytextentry',
            name='verse_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
