# Generated by Django 3.0.6 on 2020-05-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.CharField(max_length=10)),
                ('pub_name', models.CharField(max_length=50)),
                ('issue_date', models.CharField(max_length=50)),
                ('formatted_issue_date', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(null=True, upload_to='magazine-cover/')),
                ('imported', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issue_date', 'pub_name', '-pk'],
                'unique_together': {('pub', 'issue_date')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('modified', models.DateTimeField()),
                ('audio_file_link', models.URLField()),
                ('audio_file_duration', models.PositiveIntegerField()),
                ('audio_file_bitrate', models.PositiveIntegerField()),
                ('audio_file_mimetype', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='magazine-articles/')),
                ('imported', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='magazines.Issue')),
            ],
            options={
                'ordering': ['-imported', '-pk'],
            },
        ),
    ]
