# Generated by Django 3.0.6 on 2020-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-issue', 'track', 'pk']},
        ),
        migrations.AddField(
            model_name='article',
            name='track',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='audio_file',
            field=models.FileField(null=True, upload_to='magazine-articles/'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('issue', 'track')},
        ),
    ]
