# Generated by Django 3.0.6 on 2020-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_auto_20200525_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='audio_file',
            field=models.FileField(null=True, upload_to='magazine-issues/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='audio_file_duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
