# Generated by Django 3.0.6 on 2020-05-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=50, unique=True)),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('mid', models.CharField(blank=True, max_length=50, null=True)),
                ('audio_file_link', models.URLField()),
                ('audio_file_duration', models.PositiveIntegerField()),
                ('audio_file_mimetype', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-pub_date', '-pk'],
            },
        ),
    ]
