# Generated by Django 3.0.6 on 2020-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsnew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio_file_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='audio_file_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='audio_file_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
